---
- hosts: ingeborg
  
  tasks:
    
  - name: Install required packages for using the nmcli-module
    sudo: true
    apt: name={{item}} state=installed
    with_items:
        - network-manager
        - python-dbus
        - libnm-glib-dev   

  - name: Add an Ethernet connection with static IP configuration
    sudo: true
    nmcli:
        conn_name: ingeborg-eth1
        ifname: eth1
        type: ethernet
        ip4: 192.168.1.251
        gw4: 192.168.1.1
        state: present


