---
- hosts: all

# Denne er ikke ferdig...
# Les mer her: https://askubuntu.com/questions/846651/installing-starcraft-2-playonlinux#881411

  tasks:  





  - name: install wine with apt and make sure they are present
    sudo: true
    apt: name={{item}} state=installed
    with_items:
      - winehq-staging
      - winetricks
      - winbind
    
  - name: install some c++ libraries with winetricks
    command: winetricks corefonts vcrun2005 vcrun2008 vcrun2015
