---

#
# Set java_package parameter
#

- name: Debian | Define openjdk java_package
  set_fact:
    java_package: "{{ java.openjdk.debian_package }}"
    when: (java_package|trim == '') and (java_jdk_type == 'openjdk')

#
# Add/Update APT repository
#

- name: Debian | Add APT repo for openjdk 8
  apt_repository:
    repo: "{{ deb.debian.apt_backports_repo }}"
    state: present
when: (java_version == '8') and (java_jdk_type == 'openjdk')

- name: Debian | Update system openjdk Java version
  alternatives:
    name: java
    path: "/usr/lib/jvm/java-{{ java_version }}-openjdk-amd64/jre/bin/java"
    when: (not install_java_command|skipped) and java_set_as_default and (java_jdk_type == 'openjdk')


