---

- hosts: ingeborg

  tasks:
  - name: Update APT package manager repositories cache and upgrade
    become: true
    apt:
      update_cache: yes

  - name: Upgrade all packages to the latest version
    become: true
    apt:
      name: "*"
      state: latest